export const EgyptianCities = [
  "Cairo",
  "Alexandria",
  "Giza",
  "Shubra El Kheima",
  "Port Said",
  "Suez",
  "El-Mahalla El-Kubra",
  "Luxor",
  "Mansoura",
  "Tanta",
  "Aswan",
  "Faiyum",
  "Zagazig",
  "Ismailia",
  "Minya",
  "Damanhur",
  "Assiut",
  "Beni Suef",
  "Hurghada",
  "Kafr El Sheikh",
  "Qena",
  "Damietta",
  "Cairo Governorate",
  "New Cairo",
  "6th of October City",
  "Sharm El Sheikh",
  "Asyut",
  "Sohag",
  "Kena",
  "Banha",
  "Cairo Governorate",
  "Arish",
  "Badr",
];
